server:
  port: ${PORT:${SERVERS_PORT:0}}  # Cambia 8080 al puerto que desees por defecto

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

spring:
  jpa:
    hibernate:
      ddl-auto: update  # Cambia 'update' según tus necesidades
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_auth_db  # Cambia 'ms_auth_db' al nombre de tu base de datos
    username: root
    password:  # Añade tu contraseña si es necesaria

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8094/eureka
  instance:
    hostname: localhost
