server:
  port: 8099


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8094/eureka
  instance:
    hostname: localhost


spring:
  cloud:


    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-estudiantes-service
          uri: lb://ms-estudiantes-service
          predicates:
            - Path=/estudiantes/**
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/login/**
            - Path=/auth/register/**
            - Path=/auth/validate/**
            - Path=/auth/assign-role/**
            - Path=/auth/users/**

