spring:
  application:
    name: ms-auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/ms_auth_db
    username: root
    password: # Aquí puedes agregar tu contraseña si tu base de datos MySQL la requiere
  jpa:
    hibernate:
      ddl-auto: update  # Actualiza el esquema de la base de datos automáticamente. Úsalo con cuidado en producción.
    show-sql: true       # Muestra las consultas SQL en los logs

app:
  jwtExpirationMs: 86400000  # Expiración del token JWT (24 horas)

server:
  port: 8082  # El puerto en el que se ejecutará el ms-auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8094/eureka  # URL del servidor Eureka
    register-with-eureka: true   # Registrar este servicio en Eureka
    fetch-registry: true         # Habilitar la búsqueda de otros servicios en Eureka
  instance:
    hostname: localhost           # Nombre de host del servicio. Cambia según sea necesario.
